name: PR checks

on:
    push:
        branches: [ "main", "develop" ]
    pull_request:

env:
    commonGradleFlags: --parallel --stacktrace --no-configuration-cache --no-daemon
    detektReportPath: ./build/reports/detekt/detekt.xml
    reviewdogSetup: -f=checkstyle -name="detekt" -level=error -filter-mode=added

jobs:
    pr-checks:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Cleanup Github-Actions bot comments
                if: github.event_name == 'pull_request'
                continue-on-error: true
                run: |
                    sh ./ci/github_comments_cleanup.sh "${{ github.repository_owner }}" "${{ github.event.repository.name }}" "${{ github.event.number }}" "github-actions[bot]" "${{ secrets.GITHUB_TOKEN }}"

            -   name: Setup Reviewdog
                uses: reviewdog/action-setup@v1
                with:
                    reviewdog_version: v0.21.0

            -   name: Setup JDK 21 for build
                uses: actions/setup-java@v4
                with:
                    java-version: '21'
                    distribution: 'temurin'
                    cache: gradle

            -   name: Grant execute permission for gradlew
                run: chmod +x gradlew

            -   name: Run detekt
                id: detekt
                continue-on-error: true
                run: ./gradlew detektAll $commonGradleFlags

            -   name: Run Reviewdog for Detekt as Github Review
                if: always() && github.event_name == 'pull_request'
                env:
                    REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                run: |
                    reviewdog $reviewdogSetup -reporter=github-pr-review <$detektReportPath

            -   name: Run Reviewdog for Detekt as Github CHECK
                if: always()
                env:
                    REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                run: |
                    reviewdog $reviewdogSetup -reporter=github-pr-check <$detektReportPath

            -   name: Fail job when Detekt found issues
                if: steps.detekt.outcome == 'failure'
                run: exit 1

    assemble:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Setup JDK 21 for build
                uses: actions/setup-java@v4
                with:
                    java-version: '21'
                    distribution: 'temurin'
                    cache: gradle

            -   name: Grant execute permission for gradlew
                run: chmod +x gradlew

            -   name: Setup environment
                run: |
                    sh ci/setup_env.sh

            -   name: Build, unit tests, lint and package UI tests
                run: ./gradlew :app:assembleDebug :app:testDebugUnitTest :app:lintDebug :app:assembleDebugAndroidTest $commonGradleFlags

            -   name: Archive production artifacts
                uses: actions/upload-artifact@v4
                with:
                    name: app-debug.apk
                    path: app/build/outputs/apk/debug/app-debug.apk
